name: osx

on: [push, pull_request]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Tests
      env:
        TRAVIS_HOME: $GITHUB_WORKSPACE
        TRAVIS_BUILD_DIR: $GITHUB_WORKSPACE
        TRAVIS_JOB_ID: $GITHUB_RUN_ID
        TRAVIS_OS_NAME: osx
        TRAVIS_CPU_ARCH: amd64
        CLIENT: default
        TEST_FROM_BUILD: ${TRAVIS_BUILD_DIR}/dist/electron/Kui-darwin-x64/Kui.app/Contents/MacOS/Kui
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: ./tools/travis/install.sh && (which jq || brew install jq) && npx concurrently -n COPY 'npm run test1 core-standalone' && npx concurrently -n CORE,EDIT,SUP1,SUP2 'npm run test1 core' 'npm run test2 core-support' 'npm run test3 editor' 'npm run test4 core-support2'
